### ISSUE TITLE
Make examples presentable

### ISSUE THREAD

**Issue by justheuristic** [justheuristic/AgentNet#1]
Current version of ./examples is mostly unreadable for an unprepared english-speaking person
* Half of the text is russian <- translate to english
* Some explainations are missing, some are obsolete <- verify and fix
* Examples contain loads of repeated code
 * probably better to make a separate "problem definition" notebook and import it later

**Comment by BladeCarrier** [comment]
Basic example and multi-layer memory presentable but for visualization https://github.com/BladeCarrier/AgentNet/issues/11

**Comment by justheuristic** [comment]
done for the two basic examples
