### ISSUE TITLE
Session training: defining batches on the fly

### ISSUE THREAD

**Issue by justheuristic** [justheuristic/AgentNet#19]
Right now the architecture only allows to agent.get_sessions on a full session pool. It would be nice to be able to select a fraction of session pool and train on it.
Maybe allow to create an environment over theano variables? Or make a sort of "mask" for session_pool and allow to set it? The former seems more long-term

**Comment by BladeCarrier** [comment]
Prepared the classes; need to rewrite session ipynb next

**Comment by justheuristic** [comment]
done & tested
