### ISSUE TITLE
Assemble a python library

### ISSUE THREAD

**Issue by justheuristic** [justheuristic/AgentNet#3]
Convert the repo into a library that one can `./setup.py build install`
Find some way to download experiments on demand.
Structurize the modules into something sensible (Lasagne-like?)

**Comment by BladeCarrier** [comment]
Prepared everything, now only need setup.py

**Comment by justheuristic** [comment]
Well, i DO still need setup.py :)

**Comment by justheuristic** [comment]
done & tested
