### ISSUE TITLE
Research potential TensorFlow conversion consequences

### ISSUE THREAD

**Issue by justheuristic** [justheuristic/AgentNet#5]
How hard/beneficial will that be to convert the entire thing to TensorFlow?

**Comment by BladeCarrier** [comment]
Might cause slowdown for small batches https://www.reddit.com/r/MachineLearning/comments/48gfop/tensorflow_speed_questions/

**Comment by justheuristic** [comment]
Lasagne "decided to wait until it becomes more mature and/or faster than theano on GPU". If they do turn to TensorFlow, AgentNet conversion shall be much simpler

**Comment by justheuristic** [comment]
Closed for now
